---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: public.ecr.aws/amazonlinux/amazonlinux:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
